#!/usr/bin/env bash
# Render the documentation site into site/.
#
#   bash .github/scripts/build-docs-site.sh
#
# Lives here rather than in the shared scripts folder because the docs workflow
# runs from a checkout of this repository alone and cannot reach anything
# outside it. Runs locally too, for previewing before pushing.
#
# The site is the README rendered as the front page plus the API reference under
# /api/, generated by YARD from the comments in lib/. The reference is part of
# the site rather than an afterthought: this gem is not on rubygems.org yet, so
# nothing else hosts one, and generating it from the same commit as the prose is
# what stops the two drifting apart.
#
# docs/*.md is rendered too, when there is any. There is none yet — everything
# this library has to say is in the README — and the loop is here so that adding
# a page is adding a page rather than also editing this script.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"
OUT="site"

command -v pandoc >/dev/null || { echo "pandoc is required" >&2; exit 1; }

# The option was renamed: --highlight-style in older pandoc,
# --syntax-highlighting in newer, and each rejects or deprecates the other.
# Ubuntu's package and a current Homebrew install sit on opposite sides of that
# change, so the flag is chosen rather than assumed — hardcoding either one
# breaks the build somewhere.
if pandoc --help 2>&1 | grep -q -- '--syntax-highlighting'; then
  HIGHLIGHT=(--syntax-highlighting=tango)
else
  HIGHLIGHT=(--highlight-style=tango)
fi

rm -rf "$OUT"
mkdir -p "$OUT"

if compgen -G "docs/assets/*" > /dev/null; then
  mkdir -p "$OUT/assets"
  cp docs/assets/* "$OUT/assets/"
fi

# The README links to it by a relative path, so it has to be beside the rendered
# README rather than only in the repository. Copied as it is: a licence rendered
# to HTML is a licence somebody has reformatted.
cp LICENSE "$OUT/LICENSE"

cat > "$OUT/style.css" <<'CSS'
:root {
  color-scheme: light dark;
  --fg:#1a1a1a; --bg:#fff; --muted:#5f5f5f; --line:#e4e4e4;
  --accent:#b4451f; --code-bg:#f7f7f5; --nav-bg:#fbfbfa;
}
@media (prefers-color-scheme: dark) {
  :root { --fg:#e8e8e8; --bg:#161616; --muted:#9c9c9c; --line:#2d2d2d;
          --accent:#ff8a5c; --code-bg:#1e1e1e; --nav-bg:#1b1b1b; }
}
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--fg);
       font:16px/1.7 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; }
nav.top { background:var(--nav-bg); border-bottom:1px solid var(--line);
          padding:.85rem 1.25rem; display:flex; gap:1.15rem; flex-wrap:wrap; align-items:baseline;
          position:sticky; top:0; z-index:10; }
nav.top .brand { font-weight:700; letter-spacing:-.01em; margin-right:.5rem; }
nav.top a { color:var(--fg); text-decoration:none; font-size:.9rem; opacity:.78; }
nav.top a:hover { opacity:1; color:var(--accent); }
nav.top a.api { color:var(--accent); opacity:1; font-weight:600; margin-left:auto; }
main { max-width:52rem; margin:0 auto; padding:2.5rem 1.25rem 5rem; }
h1,h2,h3 { line-height:1.25; letter-spacing:-.015em; }
h1 { font-size:2.1rem; margin-top:0; }
h2 { font-size:1.5rem; margin-top:2.5rem; padding-top:.6rem; border-top:1px solid var(--line); }
h3 { font-size:1.15rem; margin-top:2rem; }
a { color:var(--accent); }
code { background:var(--code-bg); padding:.12em .35em; border-radius:4px; font-size:.9em; }
pre { background:var(--code-bg); padding:1rem 1.1rem; border-radius:8px; overflow-x:auto;
      border:1px solid var(--line); }
pre code { background:none; padding:0; font-size:.86rem; }
blockquote { margin:1.5rem 0; padding:.1rem 1.1rem; border-left:3px solid var(--line);
             color:var(--muted); }
table { border-collapse:collapse; width:100%; margin:1.5rem 0; font-size:.94rem; display:block;
        overflow-x:auto; }
th,td { border:1px solid var(--line); padding:.5rem .7rem; text-align:left; vertical-align:top; }
th { background:var(--code-bg); }
footer { border-top:1px solid var(--line); color:var(--muted); font-size:.85rem;
         padding:1.5rem 1.25rem; text-align:center; }
CSS

nav() {
  cat <<'NAV'
<nav class="top">
  <span class="brand">AceMQ for Ruby</span>
  <a href="index.html">Guide</a>
  <a href="https://github.com/AceMQ-Company/acemq-ruby-amqp">Source</a>
  <a class="api" href="api/index.html">API reference</a>
</nav>
NAV
}

render() {
  local source="$1" target="$2" title="$3"
  pandoc "$source" \
    --from=gfm --to=html5 --standalone "${HIGHLIGHT[@]}" \
    --metadata title="$title" \
    --css=style.css \
    --include-before-body=<(nav) \
    --include-after-body=<(printf '<footer>AceMQ for Ruby — Apache-2.0</footer>\n') \
    --output "$OUT/$target"
}

# The README is the front page. It is the document that is actually kept up to
# date, and a second copy of it under docs/ would be a second copy to forget.
render README.md index.html "AceMQ for Ruby"

if compgen -G "docs/*.md" > /dev/null; then
  for page in docs/*.md; do
    name="$(basename "$page" .md)"
    render "$page" "$name.html" "AceMQ for Ruby — $name"
  done
fi

# The API reference, from the comments in lib/. Kept out of the link check
# below: YARD generates its own frames and anchors, and checking them here would
# be this script marking another tool's homework.
if command -v yard >/dev/null; then
  yard doc --quiet --output-dir "$OUT/api" --readme README.md --no-progress lib
else
  echo "yard is not installed; the API reference will be missing" >&2
  exit 1
fi

# A published page linking to a 404 is a failure this site family has had
# before, and it went unnoticed because nothing checked. Cheap to check, so it
# is checked.
python3 - <<'PY'
import os, re, sys
pages = [f for f in os.listdir("site") if f.endswith(".html")]
broken = []
for f in pages:
    for href in re.findall(r'href="([^"]+)"', open("site/" + f).read()):
        if href.startswith(("http://", "https://", "#", "mailto:")):
            continue
        target = href.split("#")[0]
        if target and not os.path.exists(os.path.join("site", target)):
            broken.append(f"{f} -> {href}")
if broken:
    print("::error::the site links to pages that do not exist:")
    for b in broken:
        print("  " + b)
    sys.exit(1)
print(f"{len(pages)} pages, every internal link resolves")
PY
