# frozen_string_literal: true

# Copyright 2026 AceMQ.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require_relative "../ack"

module AceMQ
  module AMQP
    # Reads and writes Protocol Buffers.
    #
    # For high volume, and for a contract shared with services in other
    # languages. Messages are much smaller than JSON and parse faster, at the
    # cost of being unreadable without the schema — which is the trade, not an
    # oversight.
    #
    # == There is no codec without a message type, and there cannot be one
    #
    # Protobuf bytes describe nothing about themselves. A reader must already
    # hold the type the writer used, so this codec is built with one:
    #
    #   codec = ProtobufCodec.new(Acme::Order)
    #
    # That asymmetry with {JSONCodec}, which needs no argument at all, is the
    # difference between the formats made visible rather than an awkwardness in
    # the API. It is also why +protobuf+ is not a name {Codecs} knows: a name in
    # configuration cannot carry a class, and the Java library leaves it out of
    # its own registry for the same reason.
    #
    # A codec reads one type. Protobuf will happily parse bytes meant for one
    # message as another where the field numbers overlap, giving a wrong answer
    # rather than an error, so a queue carrying two types wants two consumers or
    # a wrapper message with a +oneof+.
    #
    # == The gem
    #
    # +google-protobuf+, required lazily and named when it is missing. The gem
    # declares no runtime dependencies, so a service publishing JSON is not made
    # to compile a protobuf runtime to do it.
    class ProtobufCodec
      # What this codec writes, and what Java, Go and .NET write.
      CONTENT_TYPE = "application/x-protobuf"

      # Both spellings are in use, and Go also answers for Google's own.
      ALSO_READS = ["application/protobuf", "application/vnd.google.protobuf"].freeze

      # @param message_class [Class] a class generated by +protoc+, which is
      #   what carries the schema
      # @raise [DependencyMissing] when google-protobuf is not installed
      # @raise [ArgumentError] when the class is not a generated message
      def initialize(message_class)
        load_runtime!
        unless message_class.is_a?(Class) && message_class < Google::Protobuf::MessageExts
          raise ArgumentError,
                "#{message_class.inspect} is not a class protoc generated. The protobuf " \
                "codec reads one message type, and takes the class generated from your .proto."
        end

        @message_class = message_class
        freeze
      end

      def content_type = CONTENT_TYPE

      # The message type this codec reads and writes.
      #
      # @return [Class]
      attr_reader :message_class

      # @param payload [Google::Protobuf::MessageExts]
      # @return [String] the bytes to publish
      # @raise [EncodeError] when the payload is not this codec's message type
      def encode(payload)
        unless payload.is_a?(@message_class)
          raise EncodeError,
                "the protobuf codec writes #{@message_class} and was given a " \
                "#{payload.class}. Publish the generated type, or use JSONCodec to have " \
                "an ordinary object encoded."
        end

        @message_class.encode(payload)
      end

      # @param body [String]
      # @return [Google::Protobuf::MessageExts]
      # @raise [DecodeError] when the bytes are not this message type
      def decode(body)
        @message_class.decode(body.to_s.b)
      rescue Google::Protobuf::ParseError => e
        raise DecodeError, "this message is not a #{@message_class}: #{e.message}"
      end

      # Accepts the two spellings of the protobuf media type, Google's own, and
      # any +...+protobuf+ media type.
      #
      # Never a message whose sender set no content type. Protobuf bytes are not
      # recognisable and parse quietly into nonsense more often than they fail,
      # so a codec that volunteered would report that nonsense as a success.
      def can_decode?(content_type)
        lower = content_type.to_s.downcase
        return false if lower.empty?

        lower.start_with?(CONTENT_TYPE, *ALSO_READS) || lower.include?("+protobuf")
      end

      private

      def load_runtime!
        require "google/protobuf"
      rescue LoadError => e
        raise DependencyMissing,
              "the AceMQ protobuf codec needs the google-protobuf gem, which is not " \
              "installed. Add `gem \"google-protobuf\", \"~> 4.29\"` to your Gemfile, or " \
              "run `gem install google-protobuf`. (#{e.message})"
      end
    end
  end
end
