# frozen_string_literal: true

# Copyright 2026 AceMQ.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "date"
require "json"
require "acemq/amqp"
require "acemq/amqp/patterns/schema"
require "google/protobuf/well_known_types"

# One order, encoded by the Java and Go libraries' own codecs and carried here
# as base64. Regenerated by acemq-amqp-libraries/scripts/codec-samples.sh, which
# calls those libraries' codec classes rather than reimplementing them.
#
# Why it is here at all. A codec that encodes and decodes its own output proves
# nothing about reading another language's message: both halves of the test
# share whatever the codec got wrong. Every difference these samples turned up
# was invisible to a round trip — Jackson quotes TOML strings with +'+ where
# BurntSushi uses +"+, Jackson wraps a list in an element of its own where
# +encoding/xml+ repeats the element, and the two YAML writers indent lists
# differently.
SAMPLES = JSON.parse(
  File.read(File.join(__dir__, "fixtures", "codec-samples.json"))
).freeze

# What every sample carries, minus the prose the fixture keeps beside it.
DOCUMENT = SAMPLES["document"].except("what").freeze
RECORD = SAMPLES["record"].except("what").freeze
ORDER_SCHEMA = JSON.generate(SAMPLES["avroSchema"]).freeze

# XML has no types. Everything comes back as text, which is the format being
# honest rather than the codec being lazy.
AS_TEXT = DOCUMENT.transform_values { |held| held.is_a?(Array) ? held : held.to_s }.freeze

# @return [String] the bytes one library wrote for one format
def sample_body(producer, format)
  found = SAMPLES["samples"].find do |entry|
    entry["producer"] == producer && entry["format"] == format
  end
  raise "no #{producer} #{format} sample" unless found

  found["bodyBase64"].unpack1("m")
end

# @return [String] the content type that library set on it
def sample_type(producer, format)
  SAMPLES["samples"].find { |entry| entry["producer"] == producer && entry["format"] == format }
                    .fetch("contentType")
end

RSpec.describe AceMQ::AMQP::YAMLCodec do
  let(:codec) { described_class.new }

  it "writes the content type Java, Go and .NET write" do
    expect(codec.content_type).to eq("application/yaml")
  end

  it "reads the three spellings that predate RFC 9512, and refuses what is not YAML" do
    # The accept set is wider than the write type on purpose: a producer in
    # another stack uses whichever spelling its own library picked, and a
    # message refused here is a message that had to be readable.
    ["application/yaml", "application/yaml; charset=utf-8", "application/x-yaml",
     "text/yaml", "text/x-yaml", "application/vnd.acemq.deploy+yaml"].each do |type|
      expect(codec.can_decode?(type)).to be(true), "expected to claim #{type.inspect}"
    end
    ["application/json", "application/toml", "text/plain", "application/xml", ""].each do |type|
      expect(codec.can_decode?(type)).to be(false), "expected to refuse #{type.inspect}"
    end
  end

  it "reads what the Java library wrote" do
    expect(codec.decode(sample_body("java", "yaml"))).to eq(DOCUMENT)
  end

  it "reads what the Go library wrote, indented differently as it is" do
    # Jackson writes a list flush against the key and gopkg.in/yaml.v3 indents
    # it four spaces. Both are YAML; a codec tested only against its own output
    # would never have met the second.
    go = sample_body("go", "yaml")
    expect(go).to include("\n    - widget")
    expect(sample_body("java", "yaml")).to include("\n- widget")
    expect(codec.decode(go)).to eq(DOCUMENT)
  end

  it "goes round" do
    expect(codec.decode(codec.encode(DOCUMENT))).to eq(DOCUMENT)
  end

  it "writes no document start marker, because neither Java nor Go does" do
    expect(codec.encode(DOCUMENT)).to start_with("orderId: A-1\n")
  end

  it "refuses a body that asks it to build a Ruby object" do
    # The reason this codec uses safe_load. YAML.load on a message body is
    # remote code execution: the body says which class to instantiate.
    expect { codec.decode("--- !ruby/object:Gem::Requirement\nx: 1\n") }
      .to raise_error(AceMQ::AMQP::DecodeError, /will not build/)
  end

  it "refuses anchors and aliases unless asked, because that is how a body grows" do
    bomb = "a: &x [1, 1]\nb: *x\n"
    expect { codec.decode(bomb) }.to raise_error(AceMQ::AMQP::DecodeError, /aliases/)
    expect(described_class.new(aliases: true).decode(bomb)).to eq({ "a" => [1, 1],
                                                                    "b" => [1, 1] })
  end

  it "reads a date and a timestamp, which Java and Go both write" do
    # The cost of safe_load lands here, and refusing these would reject
    # messages the other libraries send every day.
    read = codec.decode("placed: 2026-01-02\nat: 2026-01-02T03:04:05Z\n")
    expect(read["placed"]).to eq(Date.new(2026, 1, 2))
    expect(read["at"]).to eq(Time.utc(2026, 1, 2, 3, 4, 5))
  end

  it "leaves symbols to a caller who asks for them" do
    expect { codec.decode("a: !ruby/symbol done\n") }
      .to raise_error(AceMQ::AMQP::DecodeError)
    expect(described_class.new(permitted_classes: [Symbol]).decode("a: !ruby/symbol done\n"))
      .to eq({ "a" => :done })
  end

  it "will not write a payload only Ruby could read back" do
    # Psych will serialise anything as !ruby/object:, and publishing that is
    # publishing a message no other AceMQ library can decode.
    expect { codec.encode(Struct.new(:a).new(1)) }
      .to raise_error(AceMQ::AMQP::EncodeError, /!ruby/)
  end

  it "treats a body that is not YAML as fatal" do
    expect { codec.decode("a: [1\nb: }") }.to raise_error(AceMQ::AMQP::DecodeError)
    expect(AceMQ::AMQP::DecodeError.ancestors).to include(AceMQ::AMQP::FatalError)
  end
end

RSpec.describe AceMQ::AMQP::TOMLCodec do
  let(:codec) { described_class.new }

  it "writes the content type Java, Go and .NET write" do
    expect(codec.content_type).to eq("application/toml")
  end

  it "reads text/toml as well, and refuses what is not TOML" do
    ["application/toml", "application/toml; charset=utf-8", "text/toml",
     "application/vnd.acemq.deploy+toml"].each do |type|
      expect(codec.can_decode?(type)).to be(true), "expected to claim #{type.inspect}"
    end
    ["application/json", "application/yaml", "text/plain", ""].each do |type|
      expect(codec.can_decode?(type)).to be(false), "expected to refuse #{type.inspect}"
    end
  end

  it "reads what the Java library wrote, single quotes and all" do
    # Jackson writes literal strings with ' and BurntSushi writes basic strings
    # with ". A reader that handled one of them would read half the estate.
    java = sample_body("java", "toml")
    expect(java).to include("orderId = 'A-1'")
    expect(codec.decode(java)).to eq(DOCUMENT)
  end

  it "reads what the Go library wrote" do
    go = sample_body("go", "toml")
    expect(go).to include('orderId = "A-1"')
    expect(codec.decode(go)).to eq(DOCUMENT)
  end

  it "goes round, tables and arrays of tables included" do
    payload = {
      "orderId" => "A-1", "totalCents" => 4250, "paid" => true,
      "lines" => %w[widget gasket],
      "ship" => { "city" => "Leeds", "postcode" => "LS1 1AA" },
      "items" => [{ "sku" => "w", "qty" => 1 }, { "sku" => "g", "qty" => 2 }]
    }
    expect(codec.decode(codec.encode(payload))).to eq(payload)
  end

  it "reads the corners of the format a hand-edited message reaches for" do
    read = codec.decode(<<~TOML)
      # a comment, which is most of why anyone picks TOML
      title = "a \\"quoted\\" thing"
      literal = 'no \\escape here'
      hex = 0xff
      oct = 0o755
      binary = 0b1011
      big = 1_000_000
      ratio = 6.02e23
      when_ = 2026-01-02T03:04:05Z
      day = 2026-01-02
      wall = 10:32:00
      inline = { a = 1, b = "two" }
      spread = [
        1,
        2,
      ]
      folded = """
        one \\
        line"""

      [owner.name]
      first = "Ada"
    TOML
    expect(read["title"]).to eq('a "quoted" thing')
    expect(read["literal"]).to eq("no \\escape here")
    expect(read.values_at("hex", "oct", "binary", "big")).to eq([255, 493, 11, 1_000_000])
    expect(read["ratio"]).to eq(6.02e23)
    expect(read["when_"]).to eq(Time.utc(2026, 1, 2, 3, 4, 5))
    expect(read["day"]).to eq(Date.new(2026, 1, 2))
    expect(read["wall"]).to eq("10:32:00")
    expect(read["inline"]).to eq({ "a" => 1, "b" => "two" })
    expect(read["spread"]).to eq([1, 2])
    expect(read["folded"]).to eq("  one line")
    expect(read["owner"]).to eq({ "name" => { "first" => "Ada" } })
  end

  it "does not turn a country into a boolean, which is why it sits beside YAML" do
    # The whole argument for TOML in one example. YAML 1.1 reads NO and on as
    # booleans; TOML reads a quoted string as a string and would refuse an
    # unquoted NO outright.
    expect(codec.decode(%(country = "NO"\nshipping = "on"\n)))
      .to eq({ "country" => "NO", "shipping" => "on" })
    expect(AceMQ::AMQP::YAMLCodec.new.decode("country: NO\nshipping: on\n"))
      .to eq({ "country" => false, "shipping" => true })
  end

  it "refuses a payload that is not a table, because TOML has no other document" do
    expect { codec.encode([1, 2]) }
      .to raise_error(AceMQ::AMQP::EncodeError, /the top level has to be a Hash/)
  end

  it "refuses a nil rather than dropping the key" do
    # TOML has no null. Writing nothing would lose a field silently, which is
    # the kind of thing found a fortnight later.
    expect { codec.encode({ "a" => nil }) }
      .to raise_error(AceMQ::AMQP::EncodeError, /no null/)
  end

  it "says which line it gave up on" do
    expect { codec.decode("a = 1\nb = ?\n") }
      .to raise_error(AceMQ::AMQP::DecodeError, /at line 2/)
  end
end

RSpec.describe AceMQ::AMQP::XMLCodec do
  let(:codec) { described_class.new(root: "order") }

  it "writes the content type Java and Go write" do
    expect(codec.content_type).to eq("application/xml")
  end

  it "reads text/xml and any +xml type, and refuses what is not XML" do
    ["application/xml", "application/xml; charset=utf-8", "text/xml",
     "application/vnd.acemq.order+xml", "application/soap+xml"].each do |type|
      expect(codec.can_decode?(type)).to be(true), "expected to claim #{type.inspect}"
    end
    ["application/json", "application/yaml", "text/plain", ""].each do |type|
      expect(codec.can_decode?(type)).to be(false), "expected to refuse #{type.inspect}"
    end
  end

  it "reads what the Go library wrote, whose lists are repeated elements" do
    expect(codec.decode(sample_body("go", "xml"))).to eq(AS_TEXT)
  end

  it "reads what the Java library wrote, whose lists sit inside an element of their own" do
    # Jackson and encoding/xml disagree about lists, and neither is wrong. The
    # nesting comes back as the nesting it is rather than being guessed away.
    expect(codec.decode(sample_body("java", "xml")))
      .to eq(AS_TEXT.merge("lines" => { "lines" => %w[widget gasket] }))
  end

  it "goes round" do
    expect(codec.decode(codec.encode(AS_TEXT))).to eq(AS_TEXT)
  end

  it "names the root element, because XML has no anonymous document element" do
    expect(codec.encode({ "id" => "A-1" })).to eq("<order><id>A-1</id></order>")
    expect(described_class.new.encode({ "id" => "A-1" })).to start_with("<message>")
  end

  it "escapes what has to be escaped" do
    expect(codec.decode(codec.encode({ "note" => "a < b & c" })))
      .to eq({ "note" => "a < b & c" })
  end

  it "reads attributes as keys beside the elements" do
    expect(codec.decode('<order id="A-1"><city>Leeds</city></order>'))
      .to eq({ "id" => "A-1", "city" => "Leeds" })
  end

  it "refuses a document type declaration outright" do
    # A DTD is how an XML message reads files off the machine handling it and
    # turns twelve bytes into a heap full of them. The Java codec disables DTD
    # support for the same reason; this refuses before parsing.
    entity = <<~XML
      <!DOCTYPE order [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>
      <order><id>&xxe;</id></order>
    XML
    expect { codec.decode(entity) }
      .to raise_error(AceMQ::AMQP::DecodeError, /document type declaration/)
  end

  it "refuses a key XML has no element name for" do
    expect { codec.encode({ "total cents" => 1 }) }
      .to raise_error(AceMQ::AMQP::EncodeError, /not a name XML will take/)
  end

  it "treats a body that is not XML as fatal" do
    expect { codec.decode("<order><id>A-1</order>") }
      .to raise_error(AceMQ::AMQP::DecodeError)
  end
end

RSpec.describe AceMQ::AMQP::ProtobufCodec do
  let(:codec) { described_class.new(Google::Protobuf::Struct) }

  it "writes the content type Java, Go and .NET write" do
    expect(codec.content_type).to eq("application/x-protobuf")
  end

  it "reads the other spellings in use, and refuses what is not protobuf" do
    ["application/x-protobuf", "application/protobuf",
     "application/vnd.google.protobuf", "application/vnd.acemq.order+protobuf"].each do |type|
      expect(codec.can_decode?(type)).to be(true), "expected to claim #{type.inspect}"
    end
    ["application/json", "application/octet-stream", "text/plain", ""].each do |type|
      expect(codec.can_decode?(type)).to be(false), "expected to refuse #{type.inspect}"
    end
  end

  it "reads what the Java library wrote" do
    expect(codec.decode(sample_body("java", "protobuf")).to_h)
      .to eq(RECORD.merge("totalCents" => 4250.0))
  end

  it "reads what the Go library wrote, whose fields come off a map in another order" do
    expect(codec.decode(sample_body("go", "protobuf")).to_h)
      .to eq(RECORD.merge("totalCents" => 4250.0))
  end

  it "goes round" do
    struct = Google::Protobuf::Struct.from_hash(RECORD)
    expect(codec.decode(codec.encode(struct)).to_h).to eq(struct.to_h)
  end

  it "refuses a payload that is not its message type" do
    # A queue where half the messages are one type and half another is a queue
    # nobody can read, and protobuf parses the wrong type into a wrong answer
    # rather than an error more often than not.
    expect { codec.encode({ "orderId" => "A-1" }) }
      .to raise_error(AceMQ::AMQP::EncodeError, /was given a Hash/)
  end

  it "refuses to be built around something protoc did not generate" do
    expect { described_class.new(Hash) }
      .to raise_error(ArgumentError, /not a class protoc generated/)
  end

  it "treats bytes that are not this message as fatal" do
    expect { codec.decode("\xff\xff\xff\xff") }.to raise_error(AceMQ::AMQP::DecodeError)
  end
end

RSpec.describe AceMQ::AMQP::AvroCodec do
  let(:fixed) { described_class.of(ORDER_SCHEMA) }
  let(:registry) { AceMQ::AMQP::Patterns::InMemorySchemaRegistry.new }
  let(:registered) do
    described_class.registered(registry, subject: "org.acemq.samples.Order",
                                         schema: ORDER_SCHEMA)
  end

  it "writes avro/binary with a fixed schema and application/vnd.acemq.avro with a registry" do
    # Java, Go and .NET all write these two, and which one is written says
    # which framing the bytes carry.
    expect(fixed.content_type).to eq("avro/binary")
    expect(registered.content_type).to eq("application/vnd.acemq.avro")
  end

  it "claims only its own framing, because the difference is invisible in the bytes" do
    # A registered message begins with five bytes a fixed-schema codec would
    # read as the first field: no exception, and every value wrong. Java and
    # .NET gate the accept set on the mode for this reason; Go does not.
    expect(fixed.can_decode?("avro/binary")).to be(true)
    expect(fixed.can_decode?("application/vnd.acemq.avro")).to be(false)
    expect(registered.can_decode?("application/vnd.acemq.avro")).to be(true)
    expect(registered.can_decode?("avro/binary")).to be(false)
  end

  it "takes the framing-neutral spellings in either mode" do
    ["application/avro", "application/vnd.acemq.order+avro"].each do |type|
      expect(fixed.can_decode?(type)).to be(true), "expected fixed to claim #{type.inspect}"
      expect(registered.can_decode?(type)).to be(true), "expected registered to claim #{type}"
    end
    ["application/json", "application/octet-stream", ""].each do |type|
      expect(fixed.can_decode?(type)).to be(false), "expected to refuse #{type.inspect}"
    end
  end

  it "reads the fixed-schema bytes the Java and Go libraries wrote" do
    %w[java go].each do |producer|
      expect(fixed.decode(sample_body(producer, "avro-fixed"))).to eq(RECORD)
    end
  end

  it "writes the same bytes they do" do
    # Not a round trip. Both of those libraries encoded this record with their
    # own Avro implementation, and the bytes are identical to the last one.
    expect(fixed.encode(RECORD)).to eq(sample_body("java", "avro-fixed"))
    expect(fixed.encode(RECORD)).to eq(sample_body("go", "avro-fixed"))
  end

  it "reads the registered bytes they wrote, once the schema is in the registry" do
    registry.register("org.acemq.samples.Order", "avro", ORDER_SCHEMA)
    %w[java go].each do |producer|
      expect(registered.decode(sample_body(producer, "avro-registered"))).to eq(RECORD)
    end
  end

  it "frames a schema identifier the way Confluent's clients do" do
    body = registered.encode(RECORD)
    expect(body.getbyte(0)).to eq(0)
    expect(body[1, 4].unpack1("N")).to eq(1)
    expect(body[5..]).to eq(fixed.encode(RECORD))
  end

  it "refuses the other framing rather than reading it as the wrong values" do
    registry.register("org.acemq.samples.Order", "avro", ORDER_SCHEMA)
    expect { fixed.decode(sample_body("java", "avro-registered")) }
      .to raise_error(AceMQ::AMQP::DecodeError, /carry a schema identifier/)
    expect { registered.decode(sample_body("java", "avro-fixed")) }
      .to raise_error(AceMQ::AMQP::DecodeError, /no schema identifier/)
  end

  it "resolves a producer's schema onto the consumer's, which is the point of a registry" do
    # The producer adds a field. A consumer still holding the old schema reads
    # the new message, because the writer's schema travels with it.
    newer = JSON.generate(
      SAMPLES["avroSchema"].merge(
        "fields" => SAMPLES["avroSchema"]["fields"] + [{ "name" => "note", "type" => "string" }]
      )
    )
    producer = described_class.registered(registry, subject: "org.acemq.samples.Order",
                                                    schema: newer)
    body = producer.encode(RECORD.merge("note" => "gift wrap"))
    expect(registered.decode(body)).to eq(RECORD)
  end

  it "refuses a schema that is not one" do
    expect { described_class.of("{not a schema") }
      .to raise_error(ArgumentError, /not a usable Avro schema/)
  end

  it "refuses a registry that is not one" do
    expect { described_class.registered(Object.new, subject: "s", schema: ORDER_SCHEMA) }
      .to raise_error(ArgumentError, /not a schema registry/)
  end

  it "treats a payload that does not fit the schema as fatal" do
    expect { fixed.encode({ "orderId" => 1 }) }.to raise_error(AceMQ::AMQP::EncodeError)
  end
end

RSpec.describe "the codecs together" do
  # Every codec here has to be one, checked the same way a connection checks
  # what it is handed.
  it "are all codecs by the same duck type the first three satisfy" do
    [AceMQ::AMQP::YAMLCodec.new, AceMQ::AMQP::TOMLCodec.new, AceMQ::AMQP::XMLCodec.new,
     AceMQ::AMQP::ProtobufCodec.new(Google::Protobuf::Struct),
     AceMQ::AMQP::AvroCodec.of(ORDER_SCHEMA)].each do |codec|
      expect(AceMQ::AMQP::Codec.codec?(codec)).to be(true), "#{codec.class} is not a codec"
    end
  end

  it "write, and claim, the content type Java and Go actually set on the message" do
    # Not what this library believes they set. The fixture carries the string
    # each of those codecs put on its own message, and a codec here that
    # disagreed would be a message refused for no reason a log would explain.
    registry = AceMQ::AMQP::Patterns::InMemorySchemaRegistry.new
    {
      "yaml" => AceMQ::AMQP::YAMLCodec.new,
      "toml" => AceMQ::AMQP::TOMLCodec.new,
      "xml" => AceMQ::AMQP::XMLCodec.new,
      "protobuf" => AceMQ::AMQP::ProtobufCodec.new(Google::Protobuf::Struct),
      "avro-fixed" => AceMQ::AMQP::AvroCodec.of(ORDER_SCHEMA),
      "avro-registered" => AceMQ::AMQP::AvroCodec.registered(registry, subject: "order",
                                                                       schema: ORDER_SCHEMA)
    }.each do |format, codec|
      %w[java go].each do |producer|
        sent = sample_type(producer, format)
        expect(codec.content_type).to eq(sent), "#{producer} #{format}"
        expect(codec.can_decode?(sent)).to be(true), "#{producer} #{format} sent #{sent}"
      end
    end
  end

  it "sort a mixed queue out by the content type the sender set" do
    # The reason the accept sets have to be right. A composite picks by
    # can_decode?, so a spelling this library did not think of is a message
    # nothing here will read.
    composite = AceMQ::AMQP::CompositeCodec.new(
      AceMQ::AMQP::JSONCodec.new, AceMQ::AMQP::YAMLCodec.new,
      AceMQ::AMQP::TOMLCodec.new, AceMQ::AMQP::XMLCodec.new
    )
    expect(composite.content_type).to eq("application/json")
    expect(composite.decode(sample_body("java", "yaml"), "application/yaml")).to eq(DOCUMENT)
    expect(composite.decode(sample_body("go", "toml"), "application/toml")).to eq(DOCUMENT)
    expect(composite.decode(sample_body("go", "xml"), "application/xml")).to eq(AS_TEXT)
    expect(composite.decode('{"a":1}', "application/json")).to eq({ "a" => 1 })
  end

  it "read a message that arrives under an older spelling of its type" do
    composite = AceMQ::AMQP::CompositeCodec.new(
      AceMQ::AMQP::JSONCodec.new, AceMQ::AMQP::YAMLCodec.new,
      AceMQ::AMQP::TOMLCodec.new, AceMQ::AMQP::XMLCodec.new
    )
    {
      "application/x-yaml" => "yaml", "text/yaml" => "yaml", "text/x-yaml" => "yaml",
      "application/vnd.acemq.order+yaml" => "yaml"
    }.each do |type, format|
      expect(composite.decode(sample_body("java", format), type)).to eq(DOCUMENT)
    end
    expect(composite.decode(sample_body("go", "toml"), "text/toml")).to eq(DOCUMENT)
    expect(composite.decode(sample_body("go", "xml"), "text/xml")).to eq(AS_TEXT)
  end

  it "refuse a content type none of them claims" do
    composite = AceMQ::AMQP::CompositeCodec.new(
      AceMQ::AMQP::YAMLCodec.new, AceMQ::AMQP::TOMLCodec.new, AceMQ::AMQP::XMLCodec.new
    )
    expect(composite.can_decode?("application/x-protobuf")).to be(false)
    expect { composite.decode(sample_body("go", "yaml"), "application/x-protobuf") }
      .to raise_error(AceMQ::AMQP::DecodeError, %r{application/x-protobuf})
  end

  it "answer to the names the Java and Go libraries use for them" do
    expect(AceMQ::AMQP::Codecs.build("yaml")).to be_a(AceMQ::AMQP::YAMLCodec)
    expect(AceMQ::AMQP::Codecs.build("toml")).to be_a(AceMQ::AMQP::TOMLCodec)
    expect(AceMQ::AMQP::Codecs.build("xml")).to be_a(AceMQ::AMQP::XMLCodec)
  end

  it "leave protobuf and avro out of the registry, because a name cannot carry a schema" do
    expect(AceMQ::AMQP::Codecs.names).not_to include("protobuf", "avro")
  end
end
