# frozen_string_literal: true

# Copyright 2026 AceMQ.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "json"
require "acemq/amqp"
require "acemq/amqp/patterns/schema"

# When an AceMQ library resolves an Avro message onto a reader schema, and what
# the same bytes decode to when it does not.
#
# Generated by the Java library and carried by all five, byte for byte. There is
# one rule and it is the same everywhere: resolution happens when the library
# has a reader schema to resolve onto. The languages differ only in where a
# reader schema comes from, and so in how often they have one.
#
# Ruby lands on the fixture's `resolved` column, because `registered` defaults
# `reader_schema:` to the schema it was given and therefore always holds one.
# Passing the writer's schema as `reader_schema:` reaches the other column, so
# both halves of the rule are pinned here rather than only this library's own
# default.
RESOLUTION = JSON.parse(
  File.read(File.join(__dir__, "fixtures", "avro-resolution-fixtures.json"))
).freeze

# Whether the optional avro gem is installed.
#
# The codec requires it lazily and names it when it is missing, so that this gem
# can go on declaring no runtime dependencies. A suite that exploded at load
# time on a machine without it would take that promise back, so these examples
# skip instead.
AVRO_INSTALLED = begin
  require "avro"
  true
rescue LoadError
  false
end

# A registry answering the identifiers the fixture's messages actually carry.
#
# The bodies are Confluent-framed against schema ids 101 and 102, and
# `InMemorySchemaRegistry` hands identifiers out from 1 upwards — nothing can
# ask it for 101. So the real registry is still what registers a schema, which
# is what every other Avro spec here uses, and the fixture's own ids are laid
# over the read path. That path is the whole of what these examples exercise:
# resolution is a reader-side decision, and none of it touches the wire.
class ResolutionRegistry
  # @param schemas [Hash{Integer=>String}] schema text by the identifier the
  #   fixture framed it under
  def initialize(schemas)
    @registry = AceMQ::AMQP::Patterns::InMemorySchemaRegistry.new
    @by_id = schemas.to_h do |id, definition|
      [id, AceMQ::AMQP::Patterns::SchemaDefinition.new(
        id: id, subject: "resolution", version: 1, format: "avro",
        definition: definition, fingerprint: AceMQ::AMQP::Patterns.fingerprint(definition),
        registered_at: Time.now.utc
      )]
    end
  end

  def register(subject, format, definition) = @registry.register(subject, format, definition)

  def by_id(id) = @by_id.fetch(id) { @registry.by_id(id) }
end

RSpec.describe "the Avro resolution fixture" do
  it "is the one the other four libraries are held to" do
    # Not a tautology: this file is a copy, and a copy that has quietly drifted
    # is worse than no fixture at all, because the library carrying it still
    # passes its own suite while agreeing with the wrong file in private.
    expect(RESOLUTION["generatedBy"]).to eq("acemq-java-amqp AvroResolutionFixtures")
    expect(RESOLUTION["cases"].map { |one| one["case"] })
      .to eq(%w[field-removed-by-the-writer field-added-by-the-writer])
  end

  it "says this library resolves, which is the claim the examples below check" do
    ruby = RESOLUTION["libraries"].find { |one| one["library"] == "acemq-ruby-amqp" }

    expect(ruby["column"]).to eq("resolved")
  end
end

RSpec.describe AceMQ::AMQP::AvroCodec do
  RESOLUTION["cases"].each do |fixture|
    context "the #{fixture["case"]} case" do
      before { skip "the avro gem is not installed" unless AVRO_INSTALLED }

      let(:registry) { ResolutionRegistry.new(fixture["schemaId"] => fixture["writerSchema"]) }
      let(:body) { fixture["bodyBase64"].unpack1("m") }

      # What a consumer holding a schema of its own gets: `reader_schema:` is
      # left out, so the schema given is both the one written and the one read,
      # and every message is resolved onto it.
      let(:resolving) do
        described_class.registered(registry, subject: "resolution",
                                             schema: fixture["readerSchema"])
      end

      # The other column, which this library can reach but does not take by
      # default: the reader schema is the writer's, so there is no difference
      # between the two for Avro to reconcile and the record arrives as written.
      # The codec still publishes and registers the reader's declaration — only
      # what it reads against moves.
      let(:as_written) do
        described_class.registered(registry, subject: "resolution",
                                             schema: fixture["readerSchema"],
                                             reader_schema: fixture["writerSchema"])
      end

      it "decodes to the resolved column, which is where this library lands" do
        expect(resolving.decode(body, resolving.content_type)).to eq(fixture["resolved"])
      end

      it "decodes to the writer's shape when handed the writer's schema to read against" do
        expect(as_written.decode(body, as_written.content_type)).to eq(fixture["writerShape"])
      end

      it "reads the same bytes either way, because resolution is a reader-side decision" do
        # Both columns are right about the same message. They are answering
        # different questions, and only one of the two readers was told what the
        # consumer expects.
        expect(body.getbyte(0)).to eq(0)
        expect(body[1, 4].unpack1("N")).to eq(fixture["schemaId"])
      end

      it "is two genuinely different schemas, or neither column would prove anything" do
        # Avro::Schema#== is true for two record schemas sharing a full name
        # however differently their fields are declared, and both schemas in
        # both cases share one. Compared as text, which is what the codec itself
        # does when it decides whether a failure was the schemas disagreeing.
        writer = Avro::Schema.parse(fixture["writerSchema"])
        reader = Avro::Schema.parse(fixture["readerSchema"])

        expect(writer.to_s).not_to eq(reader.to_s)
      end
    end
  end

  describe "the field the writer removed" do
    before { skip "the avro gem is not installed" unless AVRO_INSTALLED }

    let(:fixture) do
      RESOLUTION["cases"].find { |one| one["case"] == "field-removed-by-the-writer" }
    end
    let(:registry) { ResolutionRegistry.new(fixture["schemaId"] => fixture["writerSchema"]) }
    let(:body) { fixture["bodyBase64"].unpack1("m") }

    it "is filled in from the reader's own default, which was never on the wire" do
      # The case the whole feature exists for, and the one the fixture chose its
      # default for: the reader declares currency with a default of "GBP" rather
      # than "", so an unresolved decode cannot pass by accident. A field
      # defaulted to the type's zero value and a field that is simply absent
      # look identical at the assertion; "GBP" can only have come from the
      # reader schema.
      codec = described_class.registered(registry, subject: "resolution",
                                                   schema: fixture["readerSchema"])

      expect(codec.decode(body, codec.content_type).fetch("currency")).to eq("GBP")
      expect(body).not_to include("GBP")
    end

    it "is simply missing without a reader schema to fill it in from" do
      codec = described_class.registered(registry, subject: "resolution",
                                                   schema: fixture["readerSchema"],
                                                   reader_schema: fixture["writerSchema"])

      expect(codec.decode(body, codec.content_type)).not_to have_key("currency")
    end

    it "differs between the columns in a value rather than in a spare key" do
      # Which is what makes this the case that bites. The other one differs by a
      # key the reader never declared and that nobody misses.
      expect(fixture["resolved"].keys - fixture["writerShape"].keys).to eq(["currency"])
    end
  end
end
