# frozen_string_literal: true

# Copyright 2026 AceMQ.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "json"
require "acemq/amqp"

# The cross-language conformance fixture, generated by the Java library and
# carried byte for byte by all five.
#
# Why it exists, concretely: Java shipped +exponential+ with a multiplier of 5
# and 10% jitter through ten releases while Go, .NET, Python and Ruby all
# doubled with 20%, so +exponential(5, 1s, 1m)+ meant 1s, 5s, 25s, 60s in one
# library and 1s, 2s, 4s, 8s in the other four. Nobody noticed for months,
# because every library tested its own arithmetic against its own expectations
# and every suite was green. Three more divergences turned up the same way in a
# single day. All four were found by a person reading five codebases side by
# side, which is not a process.
#
# The rule for everything below: a spec that reads a number out of this file and
# compares it to the same number read out of the library proves only that both
# can read JSON. Where a value can be derived, it is derived — the doubling is
# checked as doubling, the threshold table is recomputed from the rule the
# fixture states in prose, and the rung names are rendered a second time by an
# implementation that shares no code with {AceMQ::AMQP::Naming}.
CONTRACT = JSON.parse(File.read(File.join(__dir__, "fixtures",
                                          "contract-fixtures.json"))).freeze

# Reading the fixture, and a second opinion on what it says.
module Contract
  UNITS = { "ms" => 0.001, "s" => 1.0, "m" => 60.0, "h" => 3600.0 }.freeze

  # Longest first, so 7200 seconds is two hours rather than a hundred and
  # twenty minutes.
  SCALES = [[3600, "h"], [60, "m"], [1, "s"]].freeze

  # How the fixture describes a policy, unpacked far enough to build one and to
  # work out what it should do without asking it.
  Described = Struct.new(:kind, :attempts, :initial, :ceiling, :give_up)

  module_function

  # The fixture counts in milliseconds throughout, because Java's Duration
  # renders that way and one unit everywhere beats a per-field guess.
  # {AceMQ::AMQP::RetryPolicy} counts in seconds, because that is what Ruby's
  # own +sleep+ and +Time+ arithmetic speak. Every number crosses here and
  # nowhere else: a factor of a thousand that happens to make a test pass is
  # exactly the mistake this suite exists to catch, and it is far easier to see
  # when there are two conversions to look at instead of forty.
  def seconds(millis) = millis / 1000.0

  def millis(seconds) = (seconds * 1000).round

  # "500ms", "30s", "5m", "24h".
  def duration(text)
    found = /\A(\d+(?:\.\d+)?)(ms|s|m|h)\z/.match(text.strip)
    raise ArgumentError, "no duration in #{text.inspect}" unless found

    found[1].to_f * UNITS.fetch(found[2])
  end

  # The +how+ field, which is the only place the fixture says what a policy was
  # built from. Parsed rather than hard-coded so that a schedule renamed or
  # respecified upstream is read here rather than silently ignored.
  def describe(how)
    case how
    when "none()"
      Described.new(:none, 1, 0.0, 0.0, nil)
    when /\Afixed\((\d+), (.+)\)\z/
      found = Regexp.last_match
      Described.new(:fixed, found[1].to_i, duration(found[2]), 0.0, nil)
    when /\Aexponential\((\d+), ([^,]+), ([^)]+)\)(?:\.giveUpAfter\(([^)]+)\))?\z/
      found = Regexp.last_match
      Described.new(:exponential, found[1].to_i, duration(found[2]), duration(found[3]),
                    found[4] && duration(found[4]))
    else
      raise ArgumentError,
            "the fixture describes a policy this spec cannot build: #{how.inspect}"
    end
  end

  # The Ruby policy the fixture's +how+ names.
  def policy(how)
    described = describe(how)
    case described.kind
    when :none then AceMQ::AMQP::RetryPolicy.none
    when :fixed then AceMQ::AMQP::RetryPolicy.fixed(described.attempts, described.initial)
    else exponential(described)
    end
  end

  def exponential(described)
    built = AceMQ::AMQP::RetryPolicy.exponential(described.attempts, described.initial,
                                                 described.ceiling)
    described.give_up ? built.give_up_after(described.give_up) : built
  end

  # A second implementation of the schedule, written the obvious way: start at
  # the initial delay, take the ceiling if the delay has passed it, double, go
  # again. RetryPolicy caps after multiplying rather than before; this caps
  # before. Two routes to the same list is the point, since one route agreeing
  # with itself is what let the multiplier be wrong in Java for ten releases.
  def expected_schedule(described)
    return [] if described.kind == :none
    return Array.new(described.attempts - 1) { described.initial } if described.kind == :fixed

    delay = described.initial
    Array.new(described.attempts - 1) do
      capped = described.ceiling.positive? ? [delay, described.ceiling].min : delay
      delay = capped * 2
      capped
    end
  end

  # The rule the fixture states in prose, in code: "a wait at or above the
  # threshold is held on a rung queue; anything below it, and anything zero or
  # negative, is held in the consumer. A threshold of zero sends nothing to the
  # broker, so no rung queue is ever declared".
  def waits_in_broker?(delay, threshold)
    threshold.positive? && delay.positive? && delay >= threshold
  end

  # A second implementation of the rung-naming rule, sharing no code with
  # {AceMQ::AMQP::Naming.short}: find the largest unit the whole number of
  # seconds divides into, and say the delay in that.
  def rung_name(queue, delay)
    whole = delay.floor
    scale, unit = SCALES.find { |size, _| whole >= size && (whole % size).zero? } || [1, "s"]
    "#{queue}.retry.#{whole / scale}#{unit}"
  end
end

RSpec.describe "the cross-language contract" do
  it "is the file the Java library generates, carried here unchanged" do
    expect(CONTRACT["generatedBy"]).to eq("acemq-java-amqp ContractFixtures")
  end

  it "names the two exchanges this library writes into queue arguments" do
    expect(CONTRACT["deadLetterExchange"]).to eq(AceMQ::AMQP::Naming::DEAD_LETTER_EXCHANGE)
    expect(CONTRACT["retryExchange"]).to eq(AceMQ::AMQP::Naming::RETRY_EXCHANGE)
  end

  it "agrees about where a wait stops being this process's problem" do
    expect(CONTRACT["defaultBrokerWaitThresholdMillis"])
      .to eq(Contract.millis(AceMQ::AMQP::RetryLadder::DEFAULT_THRESHOLD))
  end

  describe "the retry schedules" do
    it "covers the five policies the fixture names" do
      expect(CONTRACT["retrySchedules"].map { |entry| entry["name"] }).to eq(
        %w[exponential-uncapped exponential-capped exponential-give-up-on-age fixed none]
      )
    end

    CONTRACT["retrySchedules"].each do |entry|
      kind = Contract.describe(entry["how"]).kind

      describe entry["how"] do
        # The age limit is applied from the fixture rather than left to the
        # default, and that is a divergence in itself: Java has no way to say
        # "no age limit" so its constructors set 365 days, where Ruby, Go,
        # Python and .NET all use zero for "never". Building the policy the
        # fixture describes keeps this section about the arithmetic; the
        # defaults are compared on their own below.
        let(:policy) do
          Contract.policy(entry["how"])
                  .give_up_after(Contract.seconds(entry["maxMessageAgeMillis"]))
        end
        let(:described) { Contract.describe(entry["how"]) }

        it "allows the attempts and the jitter the fixture records" do
          expect(policy.max_attempts).to eq(entry["maxAttempts"])
          expect(policy.jitter_factor).to eq(entry["jitterFactor"])
        end

        it "has one delay for every attempt after the first" do
          # Derived rather than counted off the fixture: a schedule of n delays
          # is a policy of n + 1 deliveries, and the off-by-one there is the
          # kind that only shows up as one retry too many in production.
          expect(policy.schedule.size).to eq(entry["maxAttempts"] - 1)
          expect(entry["scheduleMillis"].size).to eq(entry["maxAttempts"] - 1)
        end

        it "produces the fixture's delays, and the same list computed a second way" do
          expect(policy.schedule.map { |delay| Contract.millis(delay) })
            .to eq(entry["scheduleMillis"])
          expect(Contract.expected_schedule(described).map { |delay| Contract.millis(delay) })
            .to eq(entry["scheduleMillis"])
        end

        if kind == :exponential
          it "doubles until it reaches the ceiling and then repeats it" do
            ceiling = Contract.millis(described.ceiling)
            entry["scheduleMillis"].each_cons(2) do |before, after|
              expect(after).to eq(before < ceiling ? [before * 2, ceiling].min : ceiling)
            end
          end
        end

        if kind == :fixed
          it "keeps the same delay every time" do
            expect(entry["scheduleMillis"].uniq).to eq([Contract.millis(described.initial)])
          end
        end

        it "puts exactly the fixture's delays on rung queues" do
          ladder = AceMQ::AMQP::RetryLadder.for(
            "orders.new", policy,
            threshold: Contract.seconds(entry["brokerWaitThresholdMillis"])
          )

          expect(ladder.rungs.map { |rung| Contract.millis(rung.delay) })
            .to eq(entry["brokerRungDelaysMillis"])
        end

        it "decides to retry exactly where the fixture does" do
          entry["decisions"].each do |decision|
            delay = policy.next_delay(decision["attempt"],
                                      Contract.seconds(decision["messageAgeMillis"]),
                                      jitter: false)

            expect(!delay.nil?).to eq(decision["retries"]),
                                   "attempt #{decision["attempt"]} at " \
                                   "#{decision["messageAgeMillis"]}ms: the fixture says " \
                                   "#{decision["retries"]}, this library says #{!delay.nil?}"
          end
        end

        it "stops on the attempt count wherever the age allows another try" do
          # The same rule the decisions encode, said once rather than read off
          # nine rows: an attempt at or past the maximum never retries, and one
          # below it always does when the message is new.
          last = entry["maxAttempts"]

          expect(policy.next_delay(last, 0.0, jitter: false)).to be_nil
          expect(policy.next_delay(last + 1, 0.0, jitter: false)).to be_nil
          expect(policy.next_delay(last - 1, 0.0, jitter: false)).not_to be_nil if last > 1
        end
      end
    end

    describe "the age limit the fixture records but this library does not have" do
      # Reported rather than papered over. Java's RetryPolicy constructors set
      # maxMessageAge to Duration.ofDays(365) because Java has no value meaning
      # "no limit"; Ruby, Go, Python and .NET all use zero for that, and all
      # four test it as `age > 0 && message_age >= age`. So a message exactly a
      # year old is dead-lettered by a Java consumer and retried by the other
      # four. Java is the odd one out, the fixture carries Java's number, and
      # nothing here is going to change to match it.
      it "gives an unqualified policy no age limit at all" do
        unqualified = [AceMQ::AMQP::RetryPolicy.exponential(5, 1.0, 86_400.0),
                       AceMQ::AMQP::RetryPolicy.fixed(4, 30.0),
                       AceMQ::AMQP::RetryPolicy.none]

        expect(unqualified.map(&:max_message_age)).to eq([0.0, 0.0, 0.0])
      end

      it "retries a message older than the year Java gives up at" do
        a_year = Contract.seconds(31_536_000_000)
        policy = AceMQ::AMQP::RetryPolicy.exponential(5, 1.0, 86_400.0)

        expect(policy.next_delay(1, a_year, jitter: false)).to eq(1.0)
        expect(policy.give_up_after(a_year).next_delay(1, a_year, jitter: false)).to be_nil
      end
    end
  end

  describe "jitter" do
    let(:section) { CONTRACT["jitter"] }
    let(:policy) do
      named = CONTRACT["retrySchedules"].find { |entry| entry["name"] == section["policy"] }
      Contract.policy(named["how"])
    end
    let(:base) { policy.schedule.first }

    it "is the factor the fixture records, spread evenly either side of one" do
      expect(policy.jitter_factor).to eq(section["factor"])
      # The multipliers are not two more numbers to trust: they are one minus
      # the factor and one plus it, which is what "both directions" means.
      expect(section["minMultiplier"]).to eq(1 - section["factor"])
      expect(section["maxMultiplier"]).to eq(1 + section["factor"])
      expect(section["appliesInBothDirections"]).to be(true)
    end

    it "moves a wait in both directions and never outside the bounds it claims" do
      # Sampled rather than read back. The fixture's numbers are bounds, and the
      # only way to know this library honours a bound is to try to leave it.
      samples = Array.new(20_000) { policy.jittered(base) }

      expect(samples.min).to be < base
      expect(samples.max).to be > base
      expect(samples.min).to be >= base * section["minMultiplier"]
      expect(samples.max).to be <= base * section["maxMultiplier"]
      expect(samples.min).to be >= Contract.seconds(section["flooredAtMillis"])
    end

    it "leaves the delay alone when the caller says it names a queue" do
      expect(section["appliesToConsumerWaits"]).to be(true)
      expect(section["appliesToBrokerWaits"]).to be(false)

      unjittered = Array.new(2_000) { policy.next_delay(1, 0.0, jitter: false) }
      jittered = Array.new(2_000) { policy.next_delay(1, 0.0, jitter: true) }

      expect(unjittered.uniq).to eq([base])
      expect(jittered.uniq.size).to be > 1
    end

    it "names the rung from the schedule, however the jitter fell" do
      # The consumer's half of the same statement. A wait spent in the broker is
      # a queue name, and a jittered number names a queue nothing declared.
      transport = FakeTransport.new
      policy = AceMQ::AMQP::RetryPolicy.fixed(3, 30.0).with_jitter(section["factor"])
      consumer = AceMQ::AMQP::Consumer.new(
        transport: transport, queue: "orders.new", codec: AceMQ::AMQP::JSONCodec.new,
        retry_policy: policy, handler: ->(_message) { AceMQ::AMQP::Ack.retry("no") }
      )

      100.times do
        delivery, = FakeDelivery.build(headers: { AceMQ::AMQP::Headers::ID => "m",
                                                  AceMQ::AMQP::Headers::ATTEMPT => 1 })
        consumer.handle(delivery)
      end

      expect(transport.published.map(&:routing_key).uniq).to eq(["orders.new.retry.30s"])
    end

    it "floors at zero rather than at the millisecond Java floors at" do
      # A fourth divergence, recorded here rather than argued with. Java's
      # applyJitter ends in Math.max(1, millis), so flooredAtMillis is 1; Ruby,
      # Go, Python and .NET all floor at zero. It bites only for a delay of a
      # millisecond or two at a jitter factor near 1, which no schedule in the
      # fixture goes anywhere near — the sampled policy above stays above 800ms.
      tiny = AceMQ::AMQP::RetryPolicy.fixed(2, 0.001).with_jitter(1.0)
      samples = Array.new(5_000) { tiny.next_delay(1, 0.0) }

      expect(samples.min).to be >= 0.0
      expect(samples.min).to be < Contract.seconds(section["flooredAtMillis"])
    end
  end

  describe "where a wait is spent" do
    let(:cases) { CONTRACT["brokerWaitThreshold"]["cases"] }

    it "is the default this library uses" do
      expect(CONTRACT["brokerWaitThreshold"]["defaultMillis"])
        .to eq(Contract.millis(AceMQ::AMQP::RetryLadder::DEFAULT_THRESHOLD))
    end

    it "covers thirty rows over three thresholds" do
      expect(cases.size).to eq(30)
      expect(cases.map { |row| row["thresholdMillis"] }.uniq).to eq([30_000, 60_000, 0])
    end

    it "says what the rule in its own prose says, recomputed" do
      # The table is checked against the sentence beside it before anything in
      # this library is asked. A table that has drifted from its own rule is a
      # table five libraries would then agree with, in unison, wrongly.
      cases.each do |row|
        recomputed = Contract.waits_in_broker?(Contract.seconds(row["delayMillis"]),
                                               Contract.seconds(row["thresholdMillis"]))

        expect(recomputed).to eq(row["waitsInBroker"]), "the rule and the table disagree at " \
                                                        "#{row.inspect}"
      end
    end

    it "sends exactly those waits to the broker and no others" do
      cases.each do |row|
        delay = Contract.seconds(row["delayMillis"])
        threshold = Contract.seconds(row["thresholdMillis"])
        # A policy whose whole schedule is this one delay, so the ladder has a
        # rung to offer if the threshold means it should.
        policy = AceMQ::AMQP::RetryPolicy.new(max_attempts: 2, initial_delay: delay,
                                              multiplier: 1.0)
        ladder = AceMQ::AMQP::RetryLadder.for("orders.new", policy, threshold: threshold)

        expect(!ladder.rung_for(delay).nil?).to eq(row["waitsInBroker"]),
                                                "at threshold #{row["thresholdMillis"]}ms a " \
                                                "delay of #{row["delayMillis"]}ms should be " \
                                                "#{row["waitsInBroker"]}"
      end
    end

    it "declares no rung at all when the threshold is zero" do
      # The half of the rule that is easy to read backwards. "Wait in the broker
      # from zero" sounds like everything and means nothing: zero switches the
      # broker off, which is the only spelling there is for "never use it".
      policy = AceMQ::AMQP::RetryPolicy.exponential(6, 10.0, 300.0)

      expect(AceMQ::AMQP::RetryLadder.for("orders.new", policy, threshold: 0)).to be_empty
    end
  end

  describe "the names" do
    let(:section) { CONTRACT["naming"] }

    it "puts dead letters and parked messages under the queue they came from" do
      queue = section["queue"]

      expect(AceMQ::AMQP::Naming.dead_letter_queue(queue)).to eq(section["deadLetterQueue"])
      expect(AceMQ::AMQP::Naming.parked_queue(queue)).to eq(section["parkedQueue"])
      # Derived: the fixture's two names are the queue plus this library's two
      # suffixes, so a suffix changed here fails without the fixture being read
      # for the answer.
      expect(section["deadLetterQueue"])
        .to eq(queue + AceMQ::AMQP::Naming::DEAD_LETTER_SUFFIX)
      expect(section["parkedQueue"]).to eq(queue + AceMQ::AMQP::Naming::PARKED_SUFFIX)
    end

    it "renders every rung of a second or more the way the fixture does" do
      whole_seconds = section["retryQueues"].reject { |row| row["delayMillis"] < 1000 }

      expect(whole_seconds.size).to eq(5)
      whole_seconds.each do |row|
        delay = Contract.seconds(row["delayMillis"])

        expect(AceMQ::AMQP::Naming.retry_queue(section["queue"], delay)).to eq(row["queue"])
      end
    end

    it "renders every rung the way a second implementation of the rule does" do
      section["retryQueues"].each do |row|
        delay = Contract.seconds(row["delayMillis"])

        expect(AceMQ::AMQP::Naming.retry_queue(section["queue"], delay))
          .to eq(Contract.rung_name(section["queue"], delay))
      end
    end

    it "disagrees with Java about a sub-second rung, as the fixture records" do
      # Recorded rather than resolved, and recorded on both sides: the fixture
      # says so in naming.subSecondDisagreement and this says so here. Ruby, Go
      # and Python render orders.new.retry.0s where Java renders
      # orders.new.retry.500ms. It is unreachable behind the default
      # thirty-second threshold and only appears for a policy that deliberately
      # lowers the threshold below a second, but the two names are not the same
      # queue, so neither side gets to pretend it is settled.
      row = section["retryQueues"].find { |candidate| candidate["delayMillis"] == 500 }

      expect(row["queue"]).to eq("orders.new.retry.500ms")
      expect(AceMQ::AMQP::Naming.retry_queue(section["queue"], 0.5))
        .to eq("orders.new.retry.0s")
      expect(section["subSecondDisagreement"]).to include("orders.new.retry.0s")
    end
  end

  describe "the arguments a rung queue is declared with" do
    CONTRACT["rungArguments"].each do |row|
      describe "a rung of #{row["delayMillis"]}ms" do
        let(:delay) { Contract.seconds(row["delayMillis"]) }
        let(:arguments) { AceMQ::AMQP::RetryLadder.arguments_for("orders.new", delay) }

        it "carries exactly three arguments" do
          # The count as well as the values. A fourth argument is not a richer
          # declaration, it is a PRECONDITION_FAILED for the second service to
          # declare this queue, and that service cannot then consume at all.
          expect(arguments.size).to eq(3)
          expect(row["arguments"].size).to eq(3)
          expect(arguments.keys).to eq(row["arguments"].keys)
        end

        it "expires to the source queue through the shared retry exchange" do
          expect(arguments).to eq(row["arguments"])
        end

        it "sets a time-to-live of the delay itself, in milliseconds" do
          # The one place a factor of a thousand would hide. Derived from the
          # seconds this library was handed rather than copied from the row.
          expect(arguments["x-message-ttl"]).to eq(Contract.millis(delay))
          expect(arguments["x-message-ttl"]).to eq(row["delayMillis"])
        end

        it "is what the ladder puts on the rung it builds for that delay" do
          policy = AceMQ::AMQP::RetryPolicy.fixed(2, delay)
          # A millisecond, which is how the fixture was generated: everything
          # goes to the broker, including the delays that never would.
          ladder = AceMQ::AMQP::RetryLadder.for("orders.new", policy, threshold: 0.001)

          expect(ladder.rungs.size).to eq(1)
          expect(ladder.rungs.first.arguments).to eq(row["arguments"])
        end
      end
    end
  end

  describe "the topology" do
    let(:section) { CONTRACT["topology"] }
    let(:described) do
      Contract.describe(section["policy"].sub(" at the default threshold", ""))
    end
    let(:policy) { Contract.exponential(described) }
    let(:ladder) { AceMQ::AMQP::RetryLadder.for(section["sourceQueue"], policy) }

    # The half a deployment declares before anything consumes: the exchange
    # this service reads from, its queue, the dead-letter wiring and the
    # parking queue.
    let(:by_topology) do
      recorder = DeclarationRecorder.new
      AceMQ::AMQP::Topology.new
                           .exchange("orders", :topic)
                           .queue(section["sourceQueue"], dead_letter: true)
                           .parked_queue(section["sourceQueue"])
                           .binding(section["sourceQueue"], "orders", "order.*")
                           .apply(recorder)
      recorder
    end

    # The half a consumer declares as it starts, which is the retry ladder and
    # nothing else.
    let(:by_consumer) do
      recorder = DeclarationRecorder.new
      ladder.declare(recorder)
      recorder
    end

    it "is the policy the fixture describes, with the schedule it records" do
      expect(policy.schedule.map { |delay| Contract.millis(delay) })
        .to eq(section["policyScheduleMillis"])
      expect(ladder.rungs.map { |rung| Contract.millis(rung.delay) })
        .to eq(section["policyRungDelaysMillis"])
    end

    it "declares every exchange the fixture lists, and no others" do
      declared = by_topology.exchanges.merge(by_consumer.exchanges)

      expect(declared.keys.sort).to eq(section["exchanges"].map { |row| row["name"] }.sort)
      section["exchanges"].each do |row|
        expect(declared[row["name"]].type).to eq(row["type"])
        expect(declared[row["name"]].durable).to be(row["durable"])
      end
    end

    it "declares every queue the fixture lists, with its kind and its arguments" do
      declared = by_topology.queues.merge(by_consumer.queues)

      expect(declared.keys.sort).to eq(section["queues"].map { |row| row["name"] }.sort)
      section["queues"].each do |row|
        queue = declared[row["name"]]

        expect(queue.type).to eq(row["type"])
        expect(queue.durable).to be(row["durable"])
        expect(queue.arguments).to eq(row["arguments"])
      end
    end

    it "declares every binding the fixture lists, and no others" do
      declared = by_topology.bindings + by_consumer.bindings
      listed = section["bindings"].map do |row|
        [row["queue"], row["exchange"], row["routingKey"]]
      end

      made = declared.map { |b| [b.queue, b.exchange, b.routing_key] }

      expect(made.uniq.sort).to eq(listed.sort)
    end

    it "leaves the queue, its exchange and the dead-letter wiring to the topology" do
      section["queues"].reject { |row| row["declaredBy"] == "consumer" }.each do |row|
        expect(by_topology.queues).to have_key(row["name"])
      end
      section["exchanges"].reject { |row| row["declaredBy"] == "consumer" }.each do |row|
        expect(by_topology.exchanges).to have_key(row["name"])
      end
      section["bindings"].reject { |row| row["declaredBy"] == "consumer" }.each do |row|
        expect(by_topology.bound?(row["queue"], row["exchange"], row["routingKey"])).to be(true)
      end
    end

    it "leaves the retry exchange, the rungs and the way home to the consumer" do
      # "consumer" and not "not topology". The entries marked "both" are the
      # one place Ruby's split differs from Java's, and they have a section of
      # their own below rather than a looser condition here.
      section["queues"].select { |row| row["declaredBy"] == "consumer" }.each do |row|
        expect(by_consumer.queues).to have_key(row["name"])
      end
      section["exchanges"].select { |row| row["declaredBy"] == "consumer" }.each do |row|
        expect(by_consumer.exchanges).to have_key(row["name"])
      end
      section["bindings"].select { |row| row["declaredBy"] == "consumer" }.each do |row|
        expect(by_consumer.bound?(row["queue"], row["exchange"], row["routingKey"])).to be(true)
      end
    end
  end

  describe "the entries the fixture says both halves declare" do
    # A fifth divergence, and the reason the previous example says "consumer" of
    # the rungs and stops there. Java's RetryTopology.declare also declares
    # acemq.dlx, {queue}.dlq and {queue}.parked with their bindings, so the
    # fixture marks those "both". Ruby's RetryLadder declares the retry
    # exchange, the rungs and the one binding that brings an expired message
    # home, and nothing else — which is what Go's Declare and .NET's
    # DeclareAsync do too. Java is the odd one out; this records where Ruby
    # actually stands rather than asserting a "both" that is not true here.
    let(:shared) do
      CONTRACT["topology"].values_at("exchanges", "queues").flatten
                          .select { |row| row["declaredBy"] == "both" }
                          .map { |row| row["name"] }
    end

    it "is the dead-letter exchange and the two queues hanging off it" do
      expect(shared).to eq(["acemq.dlx", "orders.new.dlq", "orders.new.parked"])
    end

    it "declares them from the topology, and not a second time from the consumer" do
      recorder = DeclarationRecorder.new
      policy = AceMQ::AMQP::RetryPolicy.exponential(6, 10.0, 300.0)
      AceMQ::AMQP::RetryLadder.for("orders.new", policy).declare(recorder)

      expect(recorder.names).to eq(["acemq.retry", "orders.new.retry.40s",
                                    "orders.new.retry.80s", "orders.new.retry.160s"])
      expect(recorder.names & shared).to be_empty
      # The one binding a consumer adds is the one that brings an expired
      # message home. The dead-letter bindings are the topology's.
      expect(recorder.bindings.map(&:exchange).uniq).to eq([AceMQ::AMQP::Naming::RETRY_EXCHANGE])
    end

    it "means a dead letter goes nowhere if no topology was ever applied" do
      # The cost of the difference, stated rather than implied. A consumer that
      # gives up republishes through the default exchange to {queue}.dlq, and an
      # undeclared queue swallows that publish without a word. Java's consumer
      # declares the queue itself and cannot lose it this way; Ruby, Go and .NET
      # all depend on the topology having been applied first. Of the two, Java's
      # is the safer behaviour and this is the one worth changing — but changing
      # what a consumer does to a broker on startup is a decision, not a
      # conformance fix, so it is recorded here and left alone.
      transport = FakeTransport.new
      transport.missing!("orders.new.dlq")
      consumer = AceMQ::AMQP::Consumer.new(
        transport: transport, queue: "orders.new", codec: AceMQ::AMQP::JSONCodec.new,
        retry_policy: AceMQ::AMQP::RetryPolicy.none,
        handler: ->(_message) { AceMQ::AMQP::Ack.retry("no") }
      )
      consumer.start(prefetch: 1, concurrency: 1, tag: nil, arguments: {})

      expect(transport.declared_queues.map(&:first)).not_to include("orders.new.dlq")
    end
  end

  describe "the kind of queue each name gets" do
    let(:section) { CONTRACT["queueTypeDefaults"] }

    it "makes a durable, named, shared queue a quorum queue" do
      expect(AceMQ::AMQP::QueueType.resolve(name: "q").first.to_s).to eq(section["sourceQueue"])
      expect(AceMQ::AMQP::QueueType.resolve(name: "q").first.to_s)
        .to eq(section["sourceQueueWithDeadLetter"])
    end

    it "leaves a queue asked for classic classic" do
      resolved = AceMQ::AMQP::QueueType.resolve(name: "q", requested: :classic)

      expect(resolved.first.to_s).to eq(section["explicitClassicQueue"])
      expect(resolved.first.to_s).to eq(section["explicitClassicQueueWithDeadLetter"])
      # And with no x-queue-type in the table at all, which is what Java sends.
      expect(resolved.last).to eq({})
    end

    it "keeps the queues this library owns around a source queue classic" do
      recorder = DeclarationRecorder.new
      AceMQ::AMQP::Topology.new
                           .queue("orders.new", dead_letter: true)
                           .parked_queue("orders.new")
                           .apply(recorder)

      expect(recorder.queues["orders.new.dlq"].type).to eq(section["deadLetterQueue"])
      expect(recorder.queues["orders.new.parked"].type).to eq(section["parkedQueue"])
      expect(recorder.queues["orders.new"].type).to eq(section["sourceQueueWithDeadLetter"])
    end

    it "keeps a retry rung classic" do
      recorder = DeclarationRecorder.new
      AceMQ::AMQP::RetryLadder.for("orders.new", AceMQ::AMQP::RetryPolicy.fixed(2, 60.0))
                              .declare(recorder)

      expect(recorder.queues["orders.new.retry.1m"].type).to eq(section["retryRung"])
    end

    it "declares everything durable" do
      expect(section["durability"]["everyDeclaredQueueIsDurable"]).to be(true)
      recorder = DeclarationRecorder.new
      AceMQ::AMQP::Topology.new
                           .queue("a")
                           .queue("b", queue_type: :classic)
                           .queue("c", dead_letter: true)
                           .parked_queue("c")
                           .apply(recorder)

      expect(recorder.queues.values.map(&:durable).uniq).to eq([true])
    end

    it "answers the question Java cannot be asked" do
      # The fixture's note says an exclusive, auto-delete or transient queue has
      # nothing to attach to in Java, and that "the ports that do offer those
      # flags must keep them classic". Ruby offers all three, so it can be asked
      # and this is the answer.
      expect(section["durability"]["exclusiveAutoDeleteOrTransient"])
        .to include("must keep them classic")
      expect(AceMQ::AMQP::QueueType.resolve(name: "q", exclusive: true).first).to eq(:classic)
      expect(AceMQ::AMQP::QueueType.resolve(name: "q", auto_delete: true).first).to eq(:classic)
      expect(AceMQ::AMQP::QueueType.resolve(name: "q", durable: false).first).to eq(:classic)
    end
  end
end
